/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package InventoryRegistration;


import InventoryRegistration.newplaceregistration;
import java.sql.ResultSet;
import java.sql.Statement;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.regex.Matcher;
import java.util.regex.Pattern;
import javax.swing.JOptionPane;

/**
 *
 * @author Piyumi
 */
public class ChairRegistration extends javax.swing.JFrame {

    /**
     * Creates new form ChairRegistration
     */
    public ChairRegistration() {
        initComponents();
        setLocationRelativeTo(null); 
        HostelNameCombo();
     
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jComboBox1 = new javax.swing.JComboBox<>();
        jComboBox2 = new javax.swing.JComboBox<>();
        jTextField2 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jLabel10 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        navigationPanel1 = new javax.swing.JPanel();
        jbtnhomemenubar1 = new javax.swing.JButton();
        jbtnlogouteditprofilemenubar1 = new javax.swing.JButton();
        jbtnmanagmentmenubar1 = new javax.swing.JButton();
        jPanellogouteditprofile1 = new javax.swing.JPanel();
        jbtnlogoutmenubar2 = new javax.swing.JButton();
        jbtneditprofilemenubar2 = new javax.swing.JButton();
        jPanelmangement1 = new javax.swing.JPanel();
        jbtnmangementstudentregistrationmenubar5 = new javax.swing.JButton();
        jbtninventrymangmentmenubar2 = new javax.swing.JButton();
        jbtnmangementstudentregistrationmenubar6 = new javax.swing.JButton();
        jbtnmangementstudentregistrationmenubar7 = new javax.swing.JButton();
        jbtnmangementstudentregistrationmenubar8 = new javax.swing.JButton();
        jTextField8 = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jPanel2.setBackground(new java.awt.Color(228, 210, 253));
        jPanel2.setPreferredSize(new java.awt.Dimension(1000, 550));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jLabel2.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel2.setText("Item Id");

        jLabel3.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel3.setText("Item Type");

        jLabel4.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel4.setText("Place");

        jLabel5.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel5.setText("Inventory Page No.");

        jLabel9.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel9.setText("Remark");

        jTextField1.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jTextField1.setText("UWU/");
        jTextField1.setToolTipText("");
        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });
        jTextField1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTextField1KeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextField1KeyTyped(evt);
            }
        });

        jComboBox1.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select Chair Type", "Hostel Chair", "Staff Chair", "Reading Chair", "Dinning Chair", "Canteen Chair" }));
        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });

        jComboBox2.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select Place" }));

        jTextField2.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N

        jButton1.setBackground(new java.awt.Color(0, 102, 51));
        jButton1.setFont(new java.awt.Font("Cambria", 1, 18)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("Submit");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jTextArea1.setColumns(20);
        jTextArea1.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        jLabel10.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 0, 0));

        jButton2.setBackground(new java.awt.Color(222, 134, 2));
        jButton2.setFont(new java.awt.Font("Cambria", 1, 18)); // NOI18N
        jButton2.setForeground(new java.awt.Color(255, 255, 255));
        jButton2.setText("Back");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setBackground(new java.awt.Color(153, 0, 0));
        jButton3.setFont(new java.awt.Font("Cambria", 1, 18)); // NOI18N
        jButton3.setForeground(new java.awt.Color(255, 255, 255));
        jButton3.setText("Clear");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel6.setText("Not Registered ?");

        jLabel8.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(0, 0, 204));
        jLabel8.setText("Add New Place");
        jLabel8.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel8MouseClicked(evt);
            }
        });

        jLabel12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/chair22.jpg"))); // NOI18N

        jLabel1.setFont(new java.awt.Font("Cambria Math", 1, 22)); // NOI18N
        jLabel1.setText("Chair Registration Form");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel2))
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                        .addGap(0, 0, Short.MAX_VALUE)
                                        .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(73, 73, 73)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jComboBox2, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 250, Short.MAX_VALUE)
                                                    .addComponent(jTextField2, javax.swing.GroupLayout.Alignment.TRAILING)
                                                    .addComponent(jLabel13, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                                .addGap(0, 0, Short.MAX_VALUE))
                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(jLabel8)
                                                .addGap(5, 5, 5))))))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jButton2)
                                .addGap(75, 75, 75)
                                .addComponent(jButton3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jButton1))
                            .addComponent(jLabel9)
                            .addComponent(jLabel5)
                            .addComponent(jLabel10, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel7, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(10, 10, 10))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel1)
                        .addGap(51, 51, 51)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 258, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(21, 21, 21))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 446, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(40, 40, 40)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 52, Short.MAX_VALUE)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jButton3)
                                    .addComponent(jButton1)
                                    .addComponent(jButton2))
                                .addGap(19, 19, 19))))))
        );

        navigationPanel1.setBackground(new java.awt.Color(228, 210, 253));

        jbtnhomemenubar1.setBackground(new java.awt.Color(0, 0, 102));
        jbtnhomemenubar1.setFont(new java.awt.Font("Cambria", 1, 14)); // NOI18N
        jbtnhomemenubar1.setForeground(new java.awt.Color(255, 255, 255));
        jbtnhomemenubar1.setText("Home");
        jbtnhomemenubar1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        jbtnlogouteditprofilemenubar1.setBackground(new java.awt.Color(0, 0, 102));
        jbtnlogouteditprofilemenubar1.setFont(new java.awt.Font("Cambria", 1, 16)); // NOI18N
        jbtnlogouteditprofilemenubar1.setForeground(new java.awt.Color(255, 255, 255));
        jbtnlogouteditprofilemenubar1.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                jbtnlogouteditprofilemenubar1MouseMoved(evt);
            }
        });
        jbtnlogouteditprofilemenubar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnlogouteditprofilemenubar1ActionPerformed(evt);
            }
        });

        jbtnmanagmentmenubar1.setBackground(new java.awt.Color(0, 0, 102));
        jbtnmanagmentmenubar1.setFont(new java.awt.Font("Cambria", 1, 14)); // NOI18N
        jbtnmanagmentmenubar1.setForeground(new java.awt.Color(255, 255, 255));
        jbtnmanagmentmenubar1.setText("Management ");
        jbtnmanagmentmenubar1.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                jbtnmanagmentmenubar1MouseDragged(evt);
            }
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                jbtnmanagmentmenubar1MouseMoved(evt);
            }
        });
        jbtnmanagmentmenubar1.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jbtnmanagmentmenubar1FocusGained(evt);
            }
        });
        jbtnmanagmentmenubar1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jbtnmanagmentmenubar1MouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jbtnmanagmentmenubar1MouseExited(evt);
            }
        });
        jbtnmanagmentmenubar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnmanagmentmenubar1ActionPerformed(evt);
            }
        });

        jPanellogouteditprofile1.setBackground(new java.awt.Color(228, 210, 253));
        jPanellogouteditprofile1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(228, 210, 253)));
        jPanellogouteditprofile1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jPanellogouteditprofile1MouseExited(evt);
            }
        });

        jbtnlogoutmenubar2.setBackground(new java.awt.Color(102, 102, 255));
        jbtnlogoutmenubar2.setFont(new java.awt.Font("Cambria", 0, 16)); // NOI18N
        jbtnlogoutmenubar2.setText("LogOut");
        jbtnlogoutmenubar2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jbtnlogoutmenubar2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jbtnlogoutmenubar2MouseEntered(evt);
            }
        });
        jbtnlogoutmenubar2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnlogoutmenubar2ActionPerformed(evt);
            }
        });

        jbtneditprofilemenubar2.setBackground(new java.awt.Color(102, 102, 255));
        jbtneditprofilemenubar2.setFont(new java.awt.Font("Cambria", 0, 16)); // NOI18N
        jbtneditprofilemenubar2.setText("Edit Profile");
        jbtneditprofilemenubar2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jbtneditprofilemenubar2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jbtneditprofilemenubar2MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jbtneditprofilemenubar2MouseExited(evt);
            }
        });
        jbtneditprofilemenubar2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtneditprofilemenubar2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanellogouteditprofile1Layout = new javax.swing.GroupLayout(jPanellogouteditprofile1);
        jPanellogouteditprofile1.setLayout(jPanellogouteditprofile1Layout);
        jPanellogouteditprofile1Layout.setHorizontalGroup(
            jPanellogouteditprofile1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanellogouteditprofile1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanellogouteditprofile1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jbtneditprofilemenubar2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jbtnlogoutmenubar2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanellogouteditprofile1Layout.setVerticalGroup(
            jPanellogouteditprofile1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanellogouteditprofile1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jbtnlogoutmenubar2, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jbtneditprofilemenubar2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanelmangement1.setBackground(new java.awt.Color(228, 210, 253));
        jPanelmangement1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(228, 210, 253)));
        jPanelmangement1.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                jPanelmangement1MouseDragged(evt);
            }
        });
        jPanelmangement1.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jPanelmangement1FocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                jPanelmangement1FocusLost(evt);
            }
        });
        jPanelmangement1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jPanelmangement1MouseExited(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                jPanelmangement1MouseReleased(evt);
            }
        });
        jPanelmangement1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jPanelmangement1KeyReleased(evt);
            }
        });

        jbtnmangementstudentregistrationmenubar5.setBackground(new java.awt.Color(102, 102, 255));
        jbtnmangementstudentregistrationmenubar5.setFont(new java.awt.Font("Cambria", 0, 16)); // NOI18N
        jbtnmangementstudentregistrationmenubar5.setText("Transfer Management");
        jbtnmangementstudentregistrationmenubar5.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jbtnmangementstudentregistrationmenubar5.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                jbtnmangementstudentregistrationmenubar5MouseMoved(evt);
            }
        });
        jbtnmangementstudentregistrationmenubar5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jbtnmangementstudentregistrationmenubar5MouseEntered(evt);
            }
        });
        jbtnmangementstudentregistrationmenubar5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnmangementstudentregistrationmenubar5ActionPerformed(evt);
            }
        });

        jbtninventrymangmentmenubar2.setBackground(new java.awt.Color(102, 102, 255));
        jbtninventrymangmentmenubar2.setFont(new java.awt.Font("Cambria", 0, 16)); // NOI18N
        jbtninventrymangmentmenubar2.setText("Inventry Management");
        jbtninventrymangmentmenubar2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jbtninventrymangmentmenubar2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jbtninventrymangmentmenubar2MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jbtninventrymangmentmenubar2MouseEntered(evt);
            }
        });
        jbtninventrymangmentmenubar2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtninventrymangmentmenubar2ActionPerformed(evt);
            }
        });

        jbtnmangementstudentregistrationmenubar6.setBackground(new java.awt.Color(102, 102, 255));
        jbtnmangementstudentregistrationmenubar6.setFont(new java.awt.Font("Cambria", 0, 16)); // NOI18N
        jbtnmangementstudentregistrationmenubar6.setText("Hostel Management");
        jbtnmangementstudentregistrationmenubar6.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jbtnmangementstudentregistrationmenubar6.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                jbtnmangementstudentregistrationmenubar6MouseMoved(evt);
            }
        });
        jbtnmangementstudentregistrationmenubar6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jbtnmangementstudentregistrationmenubar6MouseEntered(evt);
            }
        });
        jbtnmangementstudentregistrationmenubar6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnmangementstudentregistrationmenubar6ActionPerformed(evt);
            }
        });

        jbtnmangementstudentregistrationmenubar7.setBackground(new java.awt.Color(102, 102, 255));
        jbtnmangementstudentregistrationmenubar7.setFont(new java.awt.Font("Cambria", 0, 16)); // NOI18N
        jbtnmangementstudentregistrationmenubar7.setText("Student Management");
        jbtnmangementstudentregistrationmenubar7.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jbtnmangementstudentregistrationmenubar7.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                jbtnmangementstudentregistrationmenubar7MouseMoved(evt);
            }
        });
        jbtnmangementstudentregistrationmenubar7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jbtnmangementstudentregistrationmenubar7MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jbtnmangementstudentregistrationmenubar7MouseEntered(evt);
            }
        });
        jbtnmangementstudentregistrationmenubar7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnmangementstudentregistrationmenubar7ActionPerformed(evt);
            }
        });

        jbtnmangementstudentregistrationmenubar8.setBackground(new java.awt.Color(102, 102, 255));
        jbtnmangementstudentregistrationmenubar8.setFont(new java.awt.Font("Cambria", 0, 16)); // NOI18N
        jbtnmangementstudentregistrationmenubar8.setText("Degree Management");
        jbtnmangementstudentregistrationmenubar8.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jbtnmangementstudentregistrationmenubar8.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                jbtnmangementstudentregistrationmenubar8MouseMoved(evt);
            }
        });
        jbtnmangementstudentregistrationmenubar8.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jbtnmangementstudentregistrationmenubar8MouseEntered(evt);
            }
        });
        jbtnmangementstudentregistrationmenubar8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnmangementstudentregistrationmenubar8ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelmangement1Layout = new javax.swing.GroupLayout(jPanelmangement1);
        jPanelmangement1.setLayout(jPanelmangement1Layout);
        jPanelmangement1Layout.setHorizontalGroup(
            jPanelmangement1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelmangement1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelmangement1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jbtninventrymangmentmenubar2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 205, Short.MAX_VALUE)
                    .addComponent(jbtnmangementstudentregistrationmenubar5, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jbtnmangementstudentregistrationmenubar6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jbtnmangementstudentregistrationmenubar7, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jbtnmangementstudentregistrationmenubar8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanelmangement1Layout.setVerticalGroup(
            jPanelmangement1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelmangement1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jbtnmangementstudentregistrationmenubar7, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(13, 13, 13)
                .addComponent(jbtninventrymangmentmenubar2, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jbtnmangementstudentregistrationmenubar5, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jbtnmangementstudentregistrationmenubar6, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jbtnmangementstudentregistrationmenubar8, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 7, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout navigationPanel1Layout = new javax.swing.GroupLayout(navigationPanel1);
        navigationPanel1.setLayout(navigationPanel1Layout);
        navigationPanel1Layout.setHorizontalGroup(
            navigationPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(navigationPanel1Layout.createSequentialGroup()
                .addGroup(navigationPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(navigationPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(navigationPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jbtnhomemenubar1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jPanelmangement1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jbtnmanagmentmenubar1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jbtnlogouteditprofilemenubar1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jPanellogouteditprofile1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(navigationPanel1Layout.createSequentialGroup()
                        .addGap(43, 43, 43)
                        .addComponent(jTextField8, javax.swing.GroupLayout.PREFERRED_SIZE, 0, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        navigationPanel1Layout.setVerticalGroup(
            navigationPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(navigationPanel1Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jbtnhomemenubar1, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jbtnmanagmentmenubar1, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanelmangement1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jbtnlogouteditprofilemenubar1, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanellogouteditprofile1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(25, 25, 25)
                .addComponent(jTextField8, javax.swing.GroupLayout.PREFERRED_SIZE, 0, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(23, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addComponent(navigationPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(88, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(57, 57, 57)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(navigationPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 1072, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(1, 1, 1))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 584, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed

        String itemId = jTextField1.getText();
        String itemType = jComboBox1.getSelectedItem().toString();
        String place = jComboBox2.getSelectedItem().toString();
        String pageNo = jTextField2.getText();

        String remark = jTextArea1.getText();
             
       
        Date  modifiedDate = new Date();
        String date= new SimpleDateFormat("yyyy-MM-dd").format( modifiedDate);
        
         if(jTextArea1.getText().trim().isEmpty()){
            JOptionPane.showMessageDialog(rootPane,"Enter Inventory Remark" );
        }

        else if(jTextField1.getText().trim().isEmpty()){
            JOptionPane.showMessageDialog(rootPane,"Enter Item Id" );
        }
        else if(jTextField2.getText().trim().isEmpty()){
            JOptionPane.showMessageDialog(rootPane,"Enter Inventory Page Number" );
        }
         else if(jComboBox1.getSelectedItem().toString().equals("Select Chair Type")){
            JOptionPane.showMessageDialog(rootPane,"Select Item Type" );
        }  
         else if(jComboBox2.getSelectedItem().toString().equals("Select Place")){
            JOptionPane.showMessageDialog(rootPane,"Select Place" );
        }
        else{
       
       
        try {
            connectiondb c = new connectiondb();
            Statement stmt = c.getConnectiondb().createStatement();
            //
           if(itemType=="Hostel Chair"){
            
            String selectQuery="select itemid from hostelchair where itemid='"+itemId+"' ";
            ResultSet rs5=stmt.executeQuery(selectQuery);
            if(rs5.next())
            {
                   JOptionPane.showMessageDialog(rootPane,"This item is already existed" );
            }else{
               String query2 ="INSERT INTO hostelchair (itemid,place,inventorypageno,remark,lastupdateddate)VALUES('"+itemId+"','"+place+"','"+pageNo+"','"+remark+"','"+date+"')";         
               int n=0;
               n=stmt.executeUpdate(query2);
          
            if(n!=0){
                String query3 ="SELECT * FROM totalinventory WHERE itemtype = '"+itemType+"' && place = '"+place+"'";
                ResultSet rs = stmt.executeQuery(query3);
                
                if(rs.next()){
                    int sBalance2 =rs.getInt("systembalance");
                    sBalance2=sBalance2+1;
                                     
                    String query4 = "UPDATE totalinventory SET systembalance = '"+sBalance2+"' WHERE itemtype = '"+itemType+"' && place = '"+place+"'";
                
                    int n1=0;
                    n1=stmt.executeUpdate(query4);
                        if(n1!=0){
                            JOptionPane.showMessageDialog(rootPane, "Item Updated Successfully"); 
                        }
                }
                else{
                    int i=1;
                    String query5="INSERT INTO totalinventory (itemtype,systembalance,place)VALUES('"+itemType+"','"+i+"','"+place+"')";
                    int n2=0;
                    n2=stmt.executeUpdate(query5);
                
                    if(n2!=0){
                        JOptionPane.showMessageDialog(rootPane, " Registered Successfully !!!");
                    }else{
                        JOptionPane.showMessageDialog(rootPane, "Error while Hostel Chair Registration");     
                    }        
                }
            }else{
                JOptionPane.showMessageDialog(rootPane, "Error while Updating");     
            } 
           
           }   
           }
        
          
             
            //
            if(itemType=="Staff Chair"){
                  String selectQuery="select itemid from staffchair where itemid='"+itemId+"' ";
            ResultSet rs5=stmt.executeQuery(selectQuery);
            if(rs5.next())
            {
                   JOptionPane.showMessageDialog(rootPane,"This item is already existed" );
            }else{
                String query2 ="INSERT INTO staffchair (itemid,place,inventorypageno,remark,lastupdateddate)VALUES('"+itemId+"','"+place+"','"+pageNo+"','"+remark+"','"+date+"')";
              
               int n=0;
           n=stmt.executeUpdate(query2);
          
             if(n!=0){
                String query3 ="SELECT * FROM totalinventory WHERE itemtype = '"+itemType+"' && place = '"+place+"'";
                ResultSet rs = stmt.executeQuery(query3);
                
                if(rs.next()){
                    int sBalance2 =rs.getInt("systembalance");
                    sBalance2=sBalance2+1;
                                     
                    String query4 = "UPDATE totalinventory SET systembalance = '"+sBalance2+"' WHERE itemtype = '"+itemType+"' && place = '"+place+"'";
                
                    int n1=0;
                    n1=stmt.executeUpdate(query4);
                        if(n1!=0){
                            JOptionPane.showMessageDialog(rootPane, "Item Updated Successfully"); 
                        }
                }
                else{
                    int i=1;
                    String query5="INSERT INTO totalinventory (itemtype,systembalance,place)VALUES('"+itemType+"','"+i+"','"+place+"')";
                    int n2=0;
                    n2=stmt.executeUpdate(query5);
                
                    if(n2!=0){
                        JOptionPane.showMessageDialog(rootPane, "Staff Registered Successfully !!!");
                    }else{
                        JOptionPane.showMessageDialog(rootPane, "Error while Staff Chair Registration");     
                    }        
                }
            }else{
                JOptionPane.showMessageDialog(rootPane, "Error while Updating");     
            }
            } 
            }
        
            if(itemType=="Canteen Chair"){
                  String selectQuery="select itemid from canteenchair where itemid='"+itemId+"' ";
            ResultSet rs5=stmt.executeQuery(selectQuery);
            if(rs5.next())
            {
                   JOptionPane.showMessageDialog(rootPane,"This item is already existed" );
            }else{
                String query2 ="INSERT INTO canteenchair (itemid,place,inventorypageno,remark,lastupdateddate)VALUES('"+itemId+"','"+place+"','"+pageNo+"','"+remark+"','"+date+"')";

               int n=0;
           n=stmt.executeUpdate(query2);
          
             if(n!=0){
                String query3 ="SELECT * FROM totalinventory WHERE itemtype = '"+itemType+"' && place = '"+place+"'";
                ResultSet rs = stmt.executeQuery(query3);
                
                if(rs.next()){
                    int sBalance2 =rs.getInt("systembalance");
                    sBalance2=sBalance2+1;
                                     
                    String query4 = "UPDATE totalinventory SET systembalance = '"+sBalance2+"' WHERE itemtype = '"+itemType+"' && place = '"+place+"'";
                
                    int n1=0;
                    n1=stmt.executeUpdate(query4);
                        if(n1!=0){
                            JOptionPane.showMessageDialog(rootPane, "Item Updated Successfully"); 
                        }
                }
                else{
                    int i=1;
                    String query5="INSERT INTO totalinventory (itemtype,systembalance,place)VALUES('"+itemType+"','"+i+"','"+place+"')";
                    int n2=0;
                    n2=stmt.executeUpdate(query5);
                
                    if(n2!=0){
                        JOptionPane.showMessageDialog(rootPane, "Canteen Chair Registered Successfully !!!");
                    }else{
                        JOptionPane.showMessageDialog(rootPane, "Error while Canteen Chair Registration");     
                    }        
                }
            }else{
                JOptionPane.showMessageDialog(rootPane, "Error while Updating");     
            }
            }
            }
            if(itemType=="Dinning Chair"){
                  String selectQuery="select itemid from dinningchair where itemid='"+itemId+"' ";
            ResultSet rs5=stmt.executeQuery(selectQuery);
            if(rs5.next())
            {
                   JOptionPane.showMessageDialog(rootPane,"This item is already existed" );
            }else{
                String query2 ="INSERT INTO dinningchair (itemid,place,inventorypageno,remark,lastupdateddate)VALUES('"+itemId+"','"+place+"','"+pageNo+"','"+remark+"','"+date+"')";

               int n=0;
           n=stmt.executeUpdate(query2);
          
             if(n!=0){
                String query3 ="SELECT * FROM totalinventory WHERE itemtype = '"+itemType+"' && place = '"+place+"'";
                ResultSet rs = stmt.executeQuery(query3);
                
                if(rs.next()){
                    int sBalance2 =rs.getInt("systembalance");
                    sBalance2=sBalance2+1;
                                     
                    String query4 = "UPDATE totalinventory SET systembalance = '"+sBalance2+"' WHERE itemtype = '"+itemType+"' && place = '"+place+"'";
                
                    int n1=0;
                    n1=stmt.executeUpdate(query4);
                        if(n1!=0){
                            JOptionPane.showMessageDialog(rootPane, "Item Updated Successfully"); 
                        }
                }
                else{
                    int i=1;
                    String query5="INSERT INTO totalinventory (itemtype,systembalance,place)VALUES('"+itemType+"','"+i+"','"+place+"')";
                    int n2=0;
                    n2=stmt.executeUpdate(query5);
                
                    if(n2!=0){
                        JOptionPane.showMessageDialog(rootPane, "Dinning Chair Registered Successfully !!!");
                    }else{
                        JOptionPane.showMessageDialog(rootPane, "Error while Dinning Chair Registration");     
                    }        
                }
            }else{
                JOptionPane.showMessageDialog(rootPane, "Error while Updating");     
            }
            } 
            }
            if(itemType=="Reading Chair"){
                  String selectQuery="select itemid from readingchair where itemid='"+itemId+"' ";
            ResultSet rs5=stmt.executeQuery(selectQuery);
            if(rs5.next())
            {
                   JOptionPane.showMessageDialog(rootPane,"This item is already existed" );
            }else{
                String query2 ="INSERT INTO readingchair (itemid,place,inventorypageno,remark,lastupdateddate)VALUES('"+itemId+"','"+place+"','"+pageNo+"','"+remark+"','"+date+"')";

               int n=0;
           n=stmt.executeUpdate(query2);
          
             if(n!=0){
                String query3 ="SELECT * FROM totalinventory WHERE itemtype = '"+itemType+"' && place = '"+place+"'";
                ResultSet rs = stmt.executeQuery(query3);
                
                if(rs.next()){
                    int sBalance2 =rs.getInt("systembalance");
                    sBalance2=sBalance2+1;
                                     
                    String query4 = "UPDATE totalinventory SET systembalance = '"+sBalance2+"' WHERE itemtype = '"+itemType+"' && place = '"+place+"'";
                
                    int n1=0;
                    n1=stmt.executeUpdate(query4);
                        if(n1!=0){
                            JOptionPane.showMessageDialog(rootPane, "Item Updated Successfully"); 
                        }
                }
                else{
                    int i=1;
                    String query5="INSERT INTO totalinventory (itemtype,systembalance,place)VALUES('"+itemType+"','"+i+"','"+place+"')";
                    int n2=0;
                    n2=stmt.executeUpdate(query5);
                
                    if(n2!=0){
                        JOptionPane.showMessageDialog(rootPane, "Reading Chair Registered Successfully !!!");
                    }else{
                        JOptionPane.showMessageDialog(rootPane, "Error while Readinhg Chair Registration");     
                    }        
                }
            }else{
                JOptionPane.showMessageDialog(rootPane, "Error while Updating");     
            }
            }
            }
            //
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e.getMessage());
        }       
   
    }//GEN-LAST:event_jButton1ActionPerformed
    }
    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    private void jTextField1KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField1KeyTyped
            
    }//GEN-LAST:event_jTextField1KeyTyped

    private void jTextField2KeyTyped(java.awt.event.KeyEvent evt) {                                     
        String PATTERN= "^[0-9]{0,30}$";
        Pattern patt=Pattern.compile(PATTERN);
        Matcher match=patt.matcher(jTextField2.getText());
        if(!match.matches()){
        jLabel7.setText("Please use numbers only");
        }else{
        jLabel7.setText(null);
        }       
    }                                    

                        

    private void jTextArea1KeyTyped(java.awt.event.KeyEvent evt) {                                    
        String PATTERN= "^[A-Za-z]{0,30}$";
        Pattern patt=Pattern.compile(PATTERN);
        Matcher match=patt.matcher(jTextArea1.getText());
        if(!match.matches()){
        jLabel13.setText("Please use letters only");
        }else{
        jLabel13.setText(null);
    }
    }                                   
    private void jTextField1KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField1KeyPressed
    
        String PATTERN= "^[A-Za-z0-9/]{0,30}$";
        Pattern patt=Pattern.compile(PATTERN);
        Matcher match=patt.matcher(jTextField1.getText());
        if(!match.matches()){
        jLabel10.setText("Please use valid ID as UWU/FF/01");
        }else{
        jLabel10.setText(null);
        }
    }//GEN-LAST:event_jTextField1KeyPressed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
            dispose();
            new SelectInventory().setVisible(true);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
     jTextArea1.setText(" ");
     jTextField1.setText("UWU/ ");
     jTextField2.setText(" ");
     jComboBox1.setSelectedIndex(0);
     jComboBox2.setSelectedIndex(0);
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jLabel8MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel8MouseClicked
           new newplaceregistration().setVisible(true);
    }//GEN-LAST:event_jLabel8MouseClicked

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox1ActionPerformed

    private void jPanelmangement1KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jPanelmangement1KeyReleased
        //jPanel2.setVisible(false);
    }//GEN-LAST:event_jPanelmangement1KeyReleased

    private void jPanelmangement1MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanelmangement1MouseReleased
        //jPanel2.setVisible(false);
    }//GEN-LAST:event_jPanelmangement1MouseReleased

    private void jPanelmangement1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanelmangement1MouseExited
//        jPanelmangement.setVisible(false);
    }//GEN-LAST:event_jPanelmangement1MouseExited

    private void jPanelmangement1FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jPanelmangement1FocusLost
        //jPanel2.setVisible(false);
    }//GEN-LAST:event_jPanelmangement1FocusLost

    private void jPanelmangement1FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jPanelmangement1FocusGained
        //jPanel2.setVisible(true);
    }//GEN-LAST:event_jPanelmangement1FocusGained

    private void jPanelmangement1MouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanelmangement1MouseDragged
        //jPanel2.setVisible(false);
    }//GEN-LAST:event_jPanelmangement1MouseDragged

    private void jbtnmangementstudentregistrationmenubar8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnmangementstudentregistrationmenubar8ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jbtnmangementstudentregistrationmenubar8ActionPerformed

    private void jbtnmangementstudentregistrationmenubar8MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jbtnmangementstudentregistrationmenubar8MouseEntered
        // TODO add your handling code here:
        //jPanelmangement.setVisible(true);
    }//GEN-LAST:event_jbtnmangementstudentregistrationmenubar8MouseEntered

    private void jbtnmangementstudentregistrationmenubar8MouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jbtnmangementstudentregistrationmenubar8MouseMoved
        // TODO add your handling code here:
    }//GEN-LAST:event_jbtnmangementstudentregistrationmenubar8MouseMoved

    private void jbtnmangementstudentregistrationmenubar7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnmangementstudentregistrationmenubar7ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jbtnmangementstudentregistrationmenubar7ActionPerformed

    private void jbtnmangementstudentregistrationmenubar7MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jbtnmangementstudentregistrationmenubar7MouseEntered
        // TODO add your handling code here:
//        jPanelmangement.setVisible(true);
    }//GEN-LAST:event_jbtnmangementstudentregistrationmenubar7MouseEntered

    private void jbtnmangementstudentregistrationmenubar7MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jbtnmangementstudentregistrationmenubar7MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jbtnmangementstudentregistrationmenubar7MouseClicked

    private void jbtnmangementstudentregistrationmenubar7MouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jbtnmangementstudentregistrationmenubar7MouseMoved
        // TODO add your handling code here:
    }//GEN-LAST:event_jbtnmangementstudentregistrationmenubar7MouseMoved

    private void jbtnmangementstudentregistrationmenubar6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnmangementstudentregistrationmenubar6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jbtnmangementstudentregistrationmenubar6ActionPerformed

    private void jbtnmangementstudentregistrationmenubar6MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jbtnmangementstudentregistrationmenubar6MouseEntered
        // TODO add your handling code here:
  //      jPanelmangement.setVisible(true);
    }//GEN-LAST:event_jbtnmangementstudentregistrationmenubar6MouseEntered

    private void jbtnmangementstudentregistrationmenubar6MouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jbtnmangementstudentregistrationmenubar6MouseMoved
        // TODO add your handling code here:
    }//GEN-LAST:event_jbtnmangementstudentregistrationmenubar6MouseMoved

    private void jbtninventrymangmentmenubar2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtninventrymangmentmenubar2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jbtninventrymangmentmenubar2ActionPerformed

    private void jbtninventrymangmentmenubar2MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jbtninventrymangmentmenubar2MouseEntered
    //    jPanelmangement.setVisible(true);
    }//GEN-LAST:event_jbtninventrymangmentmenubar2MouseEntered

    private void jbtninventrymangmentmenubar2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jbtninventrymangmentmenubar2MouseClicked
        // TODO add your handling code here:
        //jPanelmangement.setVisible(true);
    }//GEN-LAST:event_jbtninventrymangmentmenubar2MouseClicked

    private void jbtnmangementstudentregistrationmenubar5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnmangementstudentregistrationmenubar5ActionPerformed
        // jPanel2.setVisible(true);
        //StudentRegistration s = new  StudentRegistration();
        //s.setVisible(true);
    }//GEN-LAST:event_jbtnmangementstudentregistrationmenubar5ActionPerformed

    private void jbtnmangementstudentregistrationmenubar5MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jbtnmangementstudentregistrationmenubar5MouseEntered
      //  jPanelmangement.setVisible(true);
    }//GEN-LAST:event_jbtnmangementstudentregistrationmenubar5MouseEntered

    private void jbtnmangementstudentregistrationmenubar5MouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jbtnmangementstudentregistrationmenubar5MouseMoved

    }//GEN-LAST:event_jbtnmangementstudentregistrationmenubar5MouseMoved

    private void jPanellogouteditprofile1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanellogouteditprofile1MouseExited
        //jPanellogouteditprofile.setVisible(false);
    }//GEN-LAST:event_jPanellogouteditprofile1MouseExited

    private void jbtneditprofilemenubar2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtneditprofilemenubar2ActionPerformed

        String user1 = jTextField1.getText();
        // new Adminprofile(user1).setVisible(true);
        //jPanellogouteditprofile.setVisible(false);
    }//GEN-LAST:event_jbtneditprofilemenubar2ActionPerformed

    private void jbtneditprofilemenubar2MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jbtneditprofilemenubar2MouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_jbtneditprofilemenubar2MouseExited

    private void jbtneditprofilemenubar2MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jbtneditprofilemenubar2MouseEntered
        //jPanellogouteditprofile.setVisible(true);
    }//GEN-LAST:event_jbtneditprofilemenubar2MouseEntered

    private void jbtnlogoutmenubar2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnlogoutmenubar2ActionPerformed
      //  Login l = new Login();
        dispose();
       // l.setVisible(true);
    }//GEN-LAST:event_jbtnlogoutmenubar2ActionPerformed

    private void jbtnlogoutmenubar2MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jbtnlogoutmenubar2MouseEntered
        //jPanellogouteditprofile.setVisible(true);
    }//GEN-LAST:event_jbtnlogoutmenubar2MouseEntered

    private void jbtnmanagmentmenubar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnmanagmentmenubar1ActionPerformed
        // jPanel2.setVisible(true);
    }//GEN-LAST:event_jbtnmanagmentmenubar1ActionPerformed

    private void jbtnmanagmentmenubar1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jbtnmanagmentmenubar1MouseExited
        //jPanel2.setVisible(false);
    }//GEN-LAST:event_jbtnmanagmentmenubar1MouseExited

    private void jbtnmanagmentmenubar1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jbtnmanagmentmenubar1MouseClicked
        //jPanel2.setVisible(true);
    }//GEN-LAST:event_jbtnmanagmentmenubar1MouseClicked

    private void jbtnmanagmentmenubar1FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jbtnmanagmentmenubar1FocusGained

    }//GEN-LAST:event_jbtnmanagmentmenubar1FocusGained

    private void jbtnmanagmentmenubar1MouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jbtnmanagmentmenubar1MouseMoved
        //jPanelmangement.setVisible(true);
    }//GEN-LAST:event_jbtnmanagmentmenubar1MouseMoved

    private void jbtnmanagmentmenubar1MouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jbtnmanagmentmenubar1MouseDragged
        // jPanel2.setVisible(false);
    }//GEN-LAST:event_jbtnmanagmentmenubar1MouseDragged

    private void jbtnlogouteditprofilemenubar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnlogouteditprofilemenubar1ActionPerformed
        //jPanellogouteditprofile.setVisible(true);
    }//GEN-LAST:event_jbtnlogouteditprofilemenubar1ActionPerformed

    private void jbtnlogouteditprofilemenubar1MouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jbtnlogouteditprofilemenubar1MouseMoved
        //jPanellogouteditprofile.setVisible(true);
    }//GEN-LAST:event_jbtnlogouteditprofilemenubar1MouseMoved

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ChairRegistration.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ChairRegistration.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ChairRegistration.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ChairRegistration.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ChairRegistration().setVisible(true);
            }
        });
    }
    private void HostelNameCombo(){
          try{
            connectiondb c=new connectiondb();
            Statement stmt=c.getConnectiondb().createStatement();
            String selectQuery="select hostelname from hostel";
            ResultSet rs=stmt.executeQuery(selectQuery);
            while(rs.next())
            {
                String hostelName=rs.getString("hostelname");
                jComboBox2.addItem(hostelName);
            }
          }
        catch(Exception e)
        {
            JOptionPane.showMessageDialog(null, e.getMessage());
        }
        
    }
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JComboBox<String> jComboBox2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanellogouteditprofile1;
    private javax.swing.JPanel jPanelmangement1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField8;
    private javax.swing.JButton jbtneditprofilemenubar2;
    private javax.swing.JButton jbtnhomemenubar1;
    private javax.swing.JButton jbtninventrymangmentmenubar2;
    private javax.swing.JButton jbtnlogouteditprofilemenubar1;
    private javax.swing.JButton jbtnlogoutmenubar2;
    private javax.swing.JButton jbtnmanagmentmenubar1;
    private javax.swing.JButton jbtnmangementstudentregistrationmenubar5;
    private javax.swing.JButton jbtnmangementstudentregistrationmenubar6;
    private javax.swing.JButton jbtnmangementstudentregistrationmenubar7;
    private javax.swing.JButton jbtnmangementstudentregistrationmenubar8;
    private javax.swing.JPanel navigationPanel1;
    // End of variables declaration//GEN-END:variables

    
}
