/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package HostelManagement;

import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;



/**
 *
 * @author Piyumi
 */

public class SearchYear extends javax.swing.JFrame {

        /**
     * Creates new form HostelRegistration
     */
    public SearchYear() {
        initComponents();
        addTableHeader();
       setLocationRelativeTo(null);
    }

       SearchYear(String user) {
        initComponents();
       jbtnlogouteditprofilemenubar.setText(user);
       
    }
   DefaultTableModel model;
    
      public void addTableHeader(){
        model=(DefaultTableModel) jTable2.getModel();
        Object[] newIdetifiers=new Object[]{"Hostel Name", "Student Number", "Available Student No","Availability Status"};
        model.setColumnIdentifiers(newIdetifiers);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        jPanel3 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jLabel14 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox<>();
        jButton1 = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();
        navigationPanel = new javax.swing.JPanel();
        jbtnhomemenubar = new javax.swing.JButton();
        jbtnlogouteditprofilemenubar = new javax.swing.JButton();
        jbtnmanagmentmenubar = new javax.swing.JButton();
        jPanellogouteditprofile = new javax.swing.JPanel();
        jbtnlogoutmenubar1 = new javax.swing.JButton();
        jbtneditprofilemenubar1 = new javax.swing.JButton();
        jPanelmangement = new javax.swing.JPanel();
        jbtnmangementstudentregistrationmenubar1 = new javax.swing.JButton();
        jbtninventrymangmentmenubar1 = new javax.swing.JButton();
        jbtnmangementstudentregistrationmenubar2 = new javax.swing.JButton();
        jbtnmangementstudentregistrationmenubar3 = new javax.swing.JButton();
        jbtnmangementstudentregistrationmenubar4 = new javax.swing.JButton();
        jTextField7 = new javax.swing.JTextField();

        jMenuItem1.setText("jMenuItem1");

        jMenuItem2.setText("jMenuItem2");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jPanel3.setBackground(new java.awt.Color(228, 210, 253));
        jPanel3.setPreferredSize(new java.awt.Dimension(1000, 550));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setForeground(new java.awt.Color(255, 255, 255));
        jPanel1.setPreferredSize(new java.awt.Dimension(450, 450));

        jLabel14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/FB_IMG_1465264550993.jpg"))); // NOI18N

        jLabel2.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel2.setText("Student Year");

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select Student Year", "1 Year", "2 Year", "3 Year", "4 Year" }));
        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });

        jButton1.setBackground(new java.awt.Color(0, 51, 51));
        jButton1.setFont(new java.awt.Font("Cambria", 1, 18)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("Search");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jScrollPane2.setViewportView(jTable2);

        jLabel1.setFont(new java.awt.Font("Cambria", 1, 22)); // NOI18N
        jLabel1.setText("Search Student Year");

        jButton3.setBackground(new java.awt.Color(222, 134, 2));
        jButton3.setFont(new java.awt.Font("Cambria", 1, 18)); // NOI18N
        jButton3.setForeground(new java.awt.Color(255, 255, 255));
        jButton3.setText("Back");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 302, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jButton3)
                                    .addComponent(jLabel2))
                                .addGap(30, 30, 30)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jComboBox1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 193, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jButton1, javax.swing.GroupLayout.Alignment.TRAILING)))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(68, 68, 68)
                        .addComponent(jLabel1)))
                .addGap(20, 20, 20)
                .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 332, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 410, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(40, 40, 40)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2))
                        .addGap(60, 60, 60)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButton1)
                            .addComponent(jButton3))
                        .addGap(36, 36, 36)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 189, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(20, Short.MAX_VALUE))
        );

        navigationPanel.setBackground(new java.awt.Color(228, 210, 253));

        jbtnhomemenubar.setBackground(new java.awt.Color(0, 0, 102));
        jbtnhomemenubar.setFont(new java.awt.Font("Cambria", 1, 14)); // NOI18N
        jbtnhomemenubar.setForeground(new java.awt.Color(255, 255, 255));
        jbtnhomemenubar.setText("Home");
        jbtnhomemenubar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        jbtnlogouteditprofilemenubar.setBackground(new java.awt.Color(0, 0, 102));
        jbtnlogouteditprofilemenubar.setFont(new java.awt.Font("Cambria", 1, 16)); // NOI18N
        jbtnlogouteditprofilemenubar.setForeground(new java.awt.Color(255, 255, 255));
        jbtnlogouteditprofilemenubar.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                jbtnlogouteditprofilemenubarMouseMoved(evt);
            }
        });
        jbtnlogouteditprofilemenubar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnlogouteditprofilemenubarActionPerformed(evt);
            }
        });

        jbtnmanagmentmenubar.setBackground(new java.awt.Color(0, 0, 102));
        jbtnmanagmentmenubar.setFont(new java.awt.Font("Cambria", 1, 14)); // NOI18N
        jbtnmanagmentmenubar.setForeground(new java.awt.Color(255, 255, 255));
        jbtnmanagmentmenubar.setText("Management ");
        jbtnmanagmentmenubar.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                jbtnmanagmentmenubarMouseDragged(evt);
            }
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                jbtnmanagmentmenubarMouseMoved(evt);
            }
        });
        jbtnmanagmentmenubar.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jbtnmanagmentmenubarFocusGained(evt);
            }
        });
        jbtnmanagmentmenubar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jbtnmanagmentmenubarMouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jbtnmanagmentmenubarMouseExited(evt);
            }
        });
        jbtnmanagmentmenubar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnmanagmentmenubarActionPerformed(evt);
            }
        });

        jPanellogouteditprofile.setBackground(new java.awt.Color(228, 210, 253));
        jPanellogouteditprofile.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(228, 210, 253)));
        jPanellogouteditprofile.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jPanellogouteditprofileMouseExited(evt);
            }
        });

        jbtnlogoutmenubar1.setBackground(new java.awt.Color(102, 102, 255));
        jbtnlogoutmenubar1.setFont(new java.awt.Font("Cambria", 0, 16)); // NOI18N
        jbtnlogoutmenubar1.setText("LogOut");
        jbtnlogoutmenubar1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jbtnlogoutmenubar1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jbtnlogoutmenubar1MouseEntered(evt);
            }
        });
        jbtnlogoutmenubar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnlogoutmenubar1ActionPerformed(evt);
            }
        });

        jbtneditprofilemenubar1.setBackground(new java.awt.Color(102, 102, 255));
        jbtneditprofilemenubar1.setFont(new java.awt.Font("Cambria", 0, 16)); // NOI18N
        jbtneditprofilemenubar1.setText("Edit Profile");
        jbtneditprofilemenubar1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jbtneditprofilemenubar1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jbtneditprofilemenubar1MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jbtneditprofilemenubar1MouseExited(evt);
            }
        });
        jbtneditprofilemenubar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtneditprofilemenubar1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanellogouteditprofileLayout = new javax.swing.GroupLayout(jPanellogouteditprofile);
        jPanellogouteditprofile.setLayout(jPanellogouteditprofileLayout);
        jPanellogouteditprofileLayout.setHorizontalGroup(
            jPanellogouteditprofileLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanellogouteditprofileLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanellogouteditprofileLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jbtneditprofilemenubar1, javax.swing.GroupLayout.DEFAULT_SIZE, 205, Short.MAX_VALUE)
                    .addComponent(jbtnlogoutmenubar1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanellogouteditprofileLayout.setVerticalGroup(
            jPanellogouteditprofileLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanellogouteditprofileLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jbtnlogoutmenubar1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jbtneditprofilemenubar1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanelmangement.setBackground(new java.awt.Color(228, 210, 253));
        jPanelmangement.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(228, 210, 253)));
        jPanelmangement.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                jPanelmangementMouseDragged(evt);
            }
        });
        jPanelmangement.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jPanelmangementFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                jPanelmangementFocusLost(evt);
            }
        });
        jPanelmangement.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jPanelmangementMouseExited(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                jPanelmangementMouseReleased(evt);
            }
        });
        jPanelmangement.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jPanelmangementKeyReleased(evt);
            }
        });

        jbtnmangementstudentregistrationmenubar1.setBackground(new java.awt.Color(102, 102, 255));
        jbtnmangementstudentregistrationmenubar1.setFont(new java.awt.Font("Cambria", 0, 16)); // NOI18N
        jbtnmangementstudentregistrationmenubar1.setText("Transfer Management");
        jbtnmangementstudentregistrationmenubar1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jbtnmangementstudentregistrationmenubar1.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                jbtnmangementstudentregistrationmenubar1MouseMoved(evt);
            }
        });
        jbtnmangementstudentregistrationmenubar1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jbtnmangementstudentregistrationmenubar1MouseEntered(evt);
            }
        });
        jbtnmangementstudentregistrationmenubar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnmangementstudentregistrationmenubar1ActionPerformed(evt);
            }
        });

        jbtninventrymangmentmenubar1.setBackground(new java.awt.Color(102, 102, 255));
        jbtninventrymangmentmenubar1.setFont(new java.awt.Font("Cambria", 0, 16)); // NOI18N
        jbtninventrymangmentmenubar1.setText("Inventry Management");
        jbtninventrymangmentmenubar1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jbtninventrymangmentmenubar1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jbtninventrymangmentmenubar1MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jbtninventrymangmentmenubar1MouseEntered(evt);
            }
        });
        jbtninventrymangmentmenubar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtninventrymangmentmenubar1ActionPerformed(evt);
            }
        });

        jbtnmangementstudentregistrationmenubar2.setBackground(new java.awt.Color(102, 102, 255));
        jbtnmangementstudentregistrationmenubar2.setFont(new java.awt.Font("Cambria", 0, 16)); // NOI18N
        jbtnmangementstudentregistrationmenubar2.setText("Hostel Management");
        jbtnmangementstudentregistrationmenubar2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jbtnmangementstudentregistrationmenubar2.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                jbtnmangementstudentregistrationmenubar2MouseMoved(evt);
            }
        });
        jbtnmangementstudentregistrationmenubar2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jbtnmangementstudentregistrationmenubar2MouseEntered(evt);
            }
        });
        jbtnmangementstudentregistrationmenubar2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnmangementstudentregistrationmenubar2ActionPerformed(evt);
            }
        });

        jbtnmangementstudentregistrationmenubar3.setBackground(new java.awt.Color(102, 102, 255));
        jbtnmangementstudentregistrationmenubar3.setFont(new java.awt.Font("Cambria", 0, 16)); // NOI18N
        jbtnmangementstudentregistrationmenubar3.setText("Student Management");
        jbtnmangementstudentregistrationmenubar3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jbtnmangementstudentregistrationmenubar3.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                jbtnmangementstudentregistrationmenubar3MouseMoved(evt);
            }
        });
        jbtnmangementstudentregistrationmenubar3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jbtnmangementstudentregistrationmenubar3MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jbtnmangementstudentregistrationmenubar3MouseEntered(evt);
            }
        });
        jbtnmangementstudentregistrationmenubar3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnmangementstudentregistrationmenubar3ActionPerformed(evt);
            }
        });

        jbtnmangementstudentregistrationmenubar4.setBackground(new java.awt.Color(102, 102, 255));
        jbtnmangementstudentregistrationmenubar4.setFont(new java.awt.Font("Cambria", 0, 16)); // NOI18N
        jbtnmangementstudentregistrationmenubar4.setText("Degree Management");
        jbtnmangementstudentregistrationmenubar4.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jbtnmangementstudentregistrationmenubar4.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                jbtnmangementstudentregistrationmenubar4MouseMoved(evt);
            }
        });
        jbtnmangementstudentregistrationmenubar4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jbtnmangementstudentregistrationmenubar4MouseEntered(evt);
            }
        });
        jbtnmangementstudentregistrationmenubar4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnmangementstudentregistrationmenubar4ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelmangementLayout = new javax.swing.GroupLayout(jPanelmangement);
        jPanelmangement.setLayout(jPanelmangementLayout);
        jPanelmangementLayout.setHorizontalGroup(
            jPanelmangementLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelmangementLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelmangementLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jbtninventrymangmentmenubar1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jbtnmangementstudentregistrationmenubar1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jbtnmangementstudentregistrationmenubar2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jbtnmangementstudentregistrationmenubar3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jbtnmangementstudentregistrationmenubar4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanelmangementLayout.setVerticalGroup(
            jPanelmangementLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelmangementLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jbtnmangementstudentregistrationmenubar3, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(13, 13, 13)
                .addComponent(jbtninventrymangmentmenubar1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jbtnmangementstudentregistrationmenubar1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jbtnmangementstudentregistrationmenubar2, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jbtnmangementstudentregistrationmenubar4, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 7, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout navigationPanelLayout = new javax.swing.GroupLayout(navigationPanel);
        navigationPanel.setLayout(navigationPanelLayout);
        navigationPanelLayout.setHorizontalGroup(
            navigationPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(navigationPanelLayout.createSequentialGroup()
                .addGroup(navigationPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(navigationPanelLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(navigationPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jbtnhomemenubar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jPanelmangement, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jbtnmanagmentmenubar, javax.swing.GroupLayout.DEFAULT_SIZE, 227, Short.MAX_VALUE)
                            .addComponent(jbtnlogouteditprofilemenubar, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 227, Short.MAX_VALUE)
                            .addComponent(jPanellogouteditprofile, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(navigationPanelLayout.createSequentialGroup()
                        .addGap(43, 43, 43)
                        .addComponent(jTextField7, javax.swing.GroupLayout.PREFERRED_SIZE, 0, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        navigationPanelLayout.setVerticalGroup(
            navigationPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(navigationPanelLayout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(jbtnhomemenubar, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jbtnmanagmentmenubar, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanelmangement, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jbtnlogouteditprofilemenubar, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanellogouteditprofile, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(25, 25, 25)
                .addComponent(jTextField7, javax.swing.GroupLayout.PREFERRED_SIZE, 0, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(15, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addComponent(navigationPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 696, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(navigationPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(1, 1, 1)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(50, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jbtnlogouteditprofilemenubarMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jbtnlogouteditprofilemenubarMouseMoved
        jPanellogouteditprofile.setVisible(true);
    }//GEN-LAST:event_jbtnlogouteditprofilemenubarMouseMoved

    private void jbtnlogouteditprofilemenubarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnlogouteditprofilemenubarActionPerformed
        jPanellogouteditprofile.setVisible(true);
    }//GEN-LAST:event_jbtnlogouteditprofilemenubarActionPerformed

    private void jbtnmanagmentmenubarMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jbtnmanagmentmenubarMouseDragged
        // jPanel2.setVisible(false);
    }//GEN-LAST:event_jbtnmanagmentmenubarMouseDragged

    private void jbtnmanagmentmenubarMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jbtnmanagmentmenubarMouseMoved
        jPanelmangement.setVisible(true);
    }//GEN-LAST:event_jbtnmanagmentmenubarMouseMoved

    private void jbtnmanagmentmenubarFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jbtnmanagmentmenubarFocusGained

    }//GEN-LAST:event_jbtnmanagmentmenubarFocusGained

    private void jbtnmanagmentmenubarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jbtnmanagmentmenubarMouseClicked
        //jPanel2.setVisible(true);
    }//GEN-LAST:event_jbtnmanagmentmenubarMouseClicked

    private void jbtnmanagmentmenubarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jbtnmanagmentmenubarMouseExited
        //jPanel2.setVisible(false);
    }//GEN-LAST:event_jbtnmanagmentmenubarMouseExited

    private void jbtnmanagmentmenubarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnmanagmentmenubarActionPerformed
        // jPanel2.setVisible(true);
    }//GEN-LAST:event_jbtnmanagmentmenubarActionPerformed

    private void jbtnlogoutmenubar1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jbtnlogoutmenubar1MouseEntered
        jPanellogouteditprofile.setVisible(true);
    }//GEN-LAST:event_jbtnlogoutmenubar1MouseEntered

    private void jbtnlogoutmenubar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnlogoutmenubar1ActionPerformed
/*        Login l = new Login();
        dispose();
        l.setVisible(true);*/
    }//GEN-LAST:event_jbtnlogoutmenubar1ActionPerformed

    private void jbtneditprofilemenubar1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jbtneditprofilemenubar1MouseEntered
        jPanellogouteditprofile.setVisible(true);
    }//GEN-LAST:event_jbtneditprofilemenubar1MouseEntered

    private void jbtneditprofilemenubar1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jbtneditprofilemenubar1MouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_jbtneditprofilemenubar1MouseExited

    private void jbtneditprofilemenubar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtneditprofilemenubar1ActionPerformed

       // String user1 = jTextField1.getText();
       // new Adminprofile(user1).setVisible(true);
        jPanellogouteditprofile.setVisible(false);
    }//GEN-LAST:event_jbtneditprofilemenubar1ActionPerformed

    private void jPanellogouteditprofileMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanellogouteditprofileMouseExited
        jPanellogouteditprofile.setVisible(false);
    }//GEN-LAST:event_jPanellogouteditprofileMouseExited

    private void jbtnmangementstudentregistrationmenubar1MouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jbtnmangementstudentregistrationmenubar1MouseMoved

    }//GEN-LAST:event_jbtnmangementstudentregistrationmenubar1MouseMoved

    private void jbtnmangementstudentregistrationmenubar1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jbtnmangementstudentregistrationmenubar1MouseEntered
        jPanelmangement.setVisible(true);
    }//GEN-LAST:event_jbtnmangementstudentregistrationmenubar1MouseEntered

    private void jbtnmangementstudentregistrationmenubar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnmangementstudentregistrationmenubar1ActionPerformed
        // jPanel2.setVisible(true);
        //StudentRegistration s = new  StudentRegistration();
        //s.setVisible(true);
    }//GEN-LAST:event_jbtnmangementstudentregistrationmenubar1ActionPerformed

    private void jbtninventrymangmentmenubar1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jbtninventrymangmentmenubar1MouseClicked
        // TODO add your handling code here:
        //jPanelmangement.setVisible(true);
    }//GEN-LAST:event_jbtninventrymangmentmenubar1MouseClicked

    private void jbtninventrymangmentmenubar1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jbtninventrymangmentmenubar1MouseEntered
        jPanelmangement.setVisible(true);
    }//GEN-LAST:event_jbtninventrymangmentmenubar1MouseEntered

    private void jbtninventrymangmentmenubar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtninventrymangmentmenubar1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jbtninventrymangmentmenubar1ActionPerformed

    private void jbtnmangementstudentregistrationmenubar2MouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jbtnmangementstudentregistrationmenubar2MouseMoved
        // TODO add your handling code here:
    }//GEN-LAST:event_jbtnmangementstudentregistrationmenubar2MouseMoved

    private void jbtnmangementstudentregistrationmenubar2MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jbtnmangementstudentregistrationmenubar2MouseEntered
        // TODO add your handling code here:
        jPanelmangement.setVisible(true);
    }//GEN-LAST:event_jbtnmangementstudentregistrationmenubar2MouseEntered

    private void jbtnmangementstudentregistrationmenubar2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnmangementstudentregistrationmenubar2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jbtnmangementstudentregistrationmenubar2ActionPerformed

    private void jbtnmangementstudentregistrationmenubar3MouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jbtnmangementstudentregistrationmenubar3MouseMoved
        // TODO add your handling code here:
    }//GEN-LAST:event_jbtnmangementstudentregistrationmenubar3MouseMoved

    private void jbtnmangementstudentregistrationmenubar3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jbtnmangementstudentregistrationmenubar3MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jbtnmangementstudentregistrationmenubar3MouseClicked

    private void jbtnmangementstudentregistrationmenubar3MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jbtnmangementstudentregistrationmenubar3MouseEntered
        // TODO add your handling code here:
        jPanelmangement.setVisible(true);
    }//GEN-LAST:event_jbtnmangementstudentregistrationmenubar3MouseEntered

    private void jbtnmangementstudentregistrationmenubar3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnmangementstudentregistrationmenubar3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jbtnmangementstudentregistrationmenubar3ActionPerformed

    private void jbtnmangementstudentregistrationmenubar4MouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jbtnmangementstudentregistrationmenubar4MouseMoved
        // TODO add your handling code here:
    }//GEN-LAST:event_jbtnmangementstudentregistrationmenubar4MouseMoved

    private void jbtnmangementstudentregistrationmenubar4MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jbtnmangementstudentregistrationmenubar4MouseEntered
        // TODO add your handling code here:
        jPanelmangement.setVisible(true);
    }//GEN-LAST:event_jbtnmangementstudentregistrationmenubar4MouseEntered

    private void jbtnmangementstudentregistrationmenubar4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnmangementstudentregistrationmenubar4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jbtnmangementstudentregistrationmenubar4ActionPerformed

    private void jPanelmangementMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanelmangementMouseDragged
        //jPanel2.setVisible(false);
    }//GEN-LAST:event_jPanelmangementMouseDragged

    private void jPanelmangementFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jPanelmangementFocusGained
        //jPanel2.setVisible(true);
    }//GEN-LAST:event_jPanelmangementFocusGained

    private void jPanelmangementFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jPanelmangementFocusLost
        //jPanel2.setVisible(false);
    }//GEN-LAST:event_jPanelmangementFocusLost

    private void jPanelmangementMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanelmangementMouseExited
        jPanelmangement.setVisible(false);
    }//GEN-LAST:event_jPanelmangementMouseExited

    private void jPanelmangementMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanelmangementMouseReleased
        //jPanel2.setVisible(false);
    }//GEN-LAST:event_jPanelmangementMouseReleased

    private void jPanelmangementKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jPanelmangementKeyReleased
        //jPanel2.setVisible(false);
    }//GEN-LAST:event_jPanelmangementKeyReleased

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox1ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed

        String year = jComboBox1.getSelectedItem().toString();
        try{

            connectiondb c = new connectiondb();
            Statement stmt = c.getConnectiondb().createStatement();

            String query1 = "SELECT * FROM hostel WHERE year = '"+year+"' ";
            ResultSet rs = stmt.executeQuery(query1);

            while(rs.next()){

                String hostelname=rs.getString("hostelname");
                Boolean status=rs.getBoolean("availability");
                int sno = rs.getInt("noofstudent");
                int ano = rs.getInt("noofavailablestudent");

                //new RetriveHostel(hostelname,year,sno,ano,status).setVisible(true);
                model.addRow(new Object[]{hostelname,sno,ano,status});
            }

        }catch(Exception e){
            JOptionPane.showMessageDialog(rootPane,"Error");
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        dispose();
        new SelectSearch().setVisible(true);
    }//GEN-LAST:event_jButton3ActionPerformed
                             
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {

        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SearchYear.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SearchYear.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SearchYear.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SearchYear.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SearchYear().setVisible(true);
            }
        });
        
    }    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton3;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanellogouteditprofile;
    private javax.swing.JPanel jPanelmangement;
    private javax.swing.JScrollPane jScrollPane2;
    public javax.swing.JTable jTable2;
    private javax.swing.JTextField jTextField7;
    private javax.swing.JButton jbtneditprofilemenubar1;
    private javax.swing.JButton jbtnhomemenubar;
    private javax.swing.JButton jbtninventrymangmentmenubar1;
    private javax.swing.JButton jbtnlogouteditprofilemenubar;
    private javax.swing.JButton jbtnlogoutmenubar1;
    private javax.swing.JButton jbtnmanagmentmenubar;
    private javax.swing.JButton jbtnmangementstudentregistrationmenubar1;
    private javax.swing.JButton jbtnmangementstudentregistrationmenubar2;
    private javax.swing.JButton jbtnmangementstudentregistrationmenubar3;
    private javax.swing.JButton jbtnmangementstudentregistrationmenubar4;
    private javax.swing.JPanel navigationPanel;
    // End of variables declaration//GEN-END:variables
}
